title: LTM GitHub Innovation Challenge
description: Transform ideas into impactful solutions with GitHub Copilot
theme: minima

plugins:
  - jekyll-feed

header_pages:
  - challenge.md
  - resources.md
  - faq.md
